# Change these first
owner: iskconpandavasena # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: psena.com
    url: https://psena.com
  - name: alumni.psena.com
    url: https://alumni.psena.com
  - name: kcsoc.com
    url: https://kcsoc.com
  - name: server.kcsoc.com
    url: https://server.kcsoc.com
  - name: studio.kcsoc.com
    url: https://studio.kcsoc.com
  - name: link.kcsoc.com
    url: https://link.kcsoc.com
  - name: PS Hub
    url: https://hub.psena.com
  - name: PS Hub Database
    url: https://db.hub.psena.com
  - name: Maya PS Hub
    url: https://maya.hub.psena.com
  - name: Maya PS Hub Database
    url: https://db.maya.hub.psena.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.psena.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://i1.sndcdn.com/avatars-000334130851-kzmr4v-original.jpg
  name: Pandava Sena Upptime
  introTitle: "**Uptime** for Pandava Sena Websites"
  # introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
